---
name: Fixed

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  # We have 2 copies of the same item!
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Broken indentation:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

      # Broken by having a :
      - name: "Run: A multi-line script"
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
